services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
      - "5000:5000"
    volumes:
      - ./nexus-data:/nexus-data
    restart: unless-stopped
    networks:
      - proxy

volumes:
  nexus-data:
    name: "nexus-data"

networks:
  proxy:
    name: "proxy"
    external: true