services:
  rabbitmq:
    image: rabbitmq:4.1.2-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: rabbitadmin
      RABBITMQ_DEFAULT_PASS: SuperSecret123!
      RABBITMQ_ERLANG_COOKIE: rabbitmqcookie123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - microservices-net
    restart: unless-stopped

volumes:
  rabbitmq_data:
    name: "rabbitmq_data"

networks:
  microservices-net:
    name: microservices-net
    external: true