services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    name: "proxy"
    external: true